# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lab12-BookStore' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Lab12-BookStore
  pod 'Realm'
  pod 'Toast'
end
